#!/usr/bin/with-contenv sh

## XDEBUG
if [ "$ENABLE_XDEBUG" = true ] ; then
    echo 'XDEBUG ON'
    phpenmod xdebug
else
	echo 'XDEBUG OFF'
	phpdismod xdebug
fi

exec /usr/sbin/apache2ctl -D "FOREGROUND";