#!/usr/bin/with-contenv sh

# Starter script - think bigger, like setting a custom remote, branch or tag to pull a specific set of build instructions.
# Also pending composer rework of ISLE BUILD TOOLS.

if [ "$PULL_ISLE_BUILD_TOOLS" = true ] ; then
    echo 'Pulling newest version of ISLE Drupal Islandora build tools.'
    cd /utility-scripts/isle_drupal_build_tools || exit
    git fetch --all && git pull origin master
    echo 'Done.'
fi
