#!/usr/bin/with-contenv sh

# Pending composer rework of ISLE BUILD TOOLS.
if [ "$PULL_ISLE_BUILD_TOOLS" = true ] ; then
    echo "Pulling newest version of ISLE Drupal Islandora build tools."
    cd /utility-scripts/isle_drupal_build_tools || exit
    EXISTING_BUILD=`git rev-parse --short HEAD`
    echo "Updating to $ISLE_BUILD_TOOLS_BRANCH from $ISLE_BUILD_TOOLS_REPO."
    git remote rm origin
    git remote add origin $ISLE_BUILD_TOOLS_REPO
    git fetch --all && git reset origin/$ISLE_BUILD_TOOLS_BRANCH --hard
    NEW_BUILD_HASH=`git rev-parse --short HEAD`
    echo "Done updating build_tools;\nOld build: $EXISTING_BUILD -> New build: $NEW_BUILD_HASH"
fi

## Wait for SQL.
while ! mysqladmin ping -hmysql --silent; do
    sleep 1
done

/usr/local/bin/confd -onetime -backend env
